#!/usr/bin/env python3
"""
Generates the official Cozanet / CZN whitepaper PDF.
Source of truth for content is src/pages/WhitepaperPage.tsx on the live site —
keep this script in sync whenever that page's copy changes (supply figures,
contract address, roadmap, etc).
Run: python3 generate_whitepaper.py  -> writes cozanet-whitepaper.pdf
"""
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, ListFlowable, ListItem, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER

GOLD = colors.HexColor('#B8860B')
CHARCOAL = colors.HexColor('#1A1A1A')
SLATE = colors.HexColor('#5B5F66')
LIGHT_BORDER = colors.HexColor('#E5E5E5')

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='CozTitle', fontSize=26, leading=30, textColor=CHARCOAL, fontName='Helvetica-Bold', spaceAfter=6))
styles.add(ParagraphStyle(name='CozSubtitle', fontSize=13, leading=18, textColor=SLATE, spaceAfter=14))
styles.add(ParagraphStyle(name='CozMeta', fontSize=9, leading=12, textColor=GOLD, fontName='Helvetica-Bold', spaceAfter=10))
styles.add(ParagraphStyle(name='CozH1', fontSize=16, leading=20, textColor=CHARCOAL, fontName='Helvetica-Bold', spaceBefore=18, spaceAfter=8))
styles.add(ParagraphStyle(name='CozH2', fontSize=12, leading=16, textColor=CHARCOAL, fontName='Helvetica-Bold', spaceBefore=10, spaceAfter=6))
styles.add(ParagraphStyle(name='CozBody', fontSize=10, leading=15, textColor=CHARCOAL, spaceAfter=8, alignment=TA_LEFT))
styles.add(ParagraphStyle(name='CozBullet', fontSize=10, leading=15, textColor=CHARCOAL, spaceAfter=4))
styles.add(ParagraphStyle(name='CozSmall', fontSize=8.5, leading=12, textColor=SLATE, spaceAfter=6))
styles.add(ParagraphStyle(name='CozTOC', fontSize=10.5, leading=18, textColor=CHARCOAL))

def spec_table(rows):
    data = [[Paragraph(f'<b>{k}</b>', styles['CozSmall']), Paragraph(v, styles['CozBody'])] for k, v in rows]
    t = Table(data, colWidths=[2.1 * inch, 4.2 * inch])
    t.setStyle(TableStyle([
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, LIGHT_BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    return t

def bullets(items):
    return ListFlowable(
        [ListItem(Paragraph(i, styles['CozBullet']), leftIndent=10) for i in items],
        bulletType='bullet', start='•', leftIndent=14,
    )

story = []

# Cover
story.append(Spacer(1, 0.6 * inch))
story.append(Paragraph('WHITEPAPER · V1.0 · JULY 2026', styles['CozMeta']))
story.append(Paragraph('Cozanet', styles['CozTitle']))
story.append(Paragraph('Intelligent Financial Infrastructure for the Digital Economy', styles['CozSubtitle']))
story.append(HRFlowable(width='100%', thickness=1, color=LIGHT_BORDER, spaceAfter=14))
story.append(Paragraph(
    "This document describes the Cozanet ecosystem, the AEGIS Financial Operating System, "
    "and the CZN utility token — their purpose, architecture, tokenomics, and roadmap.",
    styles['CozBody']
))
story.append(Spacer(1, 0.3 * inch))
story.append(Paragraph('Contents', styles['CozH1']))
toc = [
    "1. Abstract", "2. The Problem", "3. The Cozanet Ecosystem",
    "4. AEGIS: The Financial Operating System", "5. CZN: The Ecosystem Token",
    "6. Technology & Architecture", "7. Security & Compliance", "8. Roadmap",
    "9. Team & Governance", "10. Risk Factors & Disclaimer",
]
for item in toc:
    story.append(Paragraph(item, styles['CozTOC']))
story.append(PageBreak())

# 1. Abstract
story.append(Paragraph('1. Abstract', styles['CozH1']))
story.append(Paragraph(
    "Cozanet is building intelligent digital infrastructure that connects artificial intelligence, "
    "financial technology, and automation into a single, seamless ecosystem. Its flagship product, "
    "AEGIS, is a Financial Operating System that acts as a smart router — automatically finding and "
    "executing the best path for every financial transaction across wallets, payments, and cross-chain "
    "rails. CZN is the ecosystem's native utility token: it is used to pay and discount the fees "
    "generated by AEGIS's routing activity, and to unlock access, rewards, and — over time — governance "
    "across the Cozanet ecosystem. CZN does not route transactions and is not required for AEGIS to "
    "function; it is a utility and incentive layer on top of it.",
    styles['CozBody']
))

# 2. The Problem
story.append(Paragraph('2. The Problem', styles['CozH1']))
story.append(Paragraph(
    "Modern financial infrastructure is fragmented. Individuals and businesses juggle separate tools "
    "for payments, wallets, portfolio tracking, and cross-chain transfers — each with its own fee "
    "structure, security model, and interface. Meanwhile, blockchain-based finance remains difficult to "
    "access safely: routing a transaction efficiently across chains and liquidity sources requires "
    "expertise most users don't have. Cozanet's thesis is that these problems are solved not by another "
    "single app, but by unified infrastructure: one gateway, intelligent routing, and one incentive "
    "layer that rewards usage instead of speculation.",
    styles['CozBody']
))

# 3. The Cozanet Ecosystem
story.append(Paragraph('3. The Cozanet Ecosystem', styles['CozH1']))
story.append(Paragraph('One ecosystem, five products.', styles['CozH2']))
story.append(Paragraph(
    "Cozanet is not one application — it is infrastructure that multiple products are built on top of.",
    styles['CozBody']
))
story.append(bullets([
    "<b>AEGIS</b> — Financial Operating System: wallets, payments, portfolio, and smart routing. The flagship product.",
    "<b>AI Platform</b> — Intelligent products that augment financial analysis, automation, and decision-making.",
    "<b>Automation</b> — Workflow engine for building and deploying automated financial and business logic.",
    "<b>Developer Platform</b> — APIs, SDKs, and documentation for building on Cozanet infrastructure.",
    "<b>Enterprise</b> — Compliance-ready, white-label infrastructure for organizations at global scale.",
    "<b>CZN</b> — The native utility token that ties fees, rewards, and (future) governance together across all products.",
]))

# 4. AEGIS
story.append(Paragraph('4. AEGIS: The Financial Operating System', styles['CozH1']))
story.append(Paragraph('The smart router at the center of Cozanet.', styles['CozH2']))
story.append(Paragraph(
    "AEGIS combines wallets, payments, AI-powered insights, portfolio management, and cross-chain "
    "operations into one system. Its core function is intelligent routing: every transaction is "
    "analyzed and directed along the most efficient available path — the best combination of cost, "
    "speed, and liquidity — instead of requiring the user to make that decision manually.",
    styles['CozBody']
))
story.append(Paragraph(
    "AEGIS is built on a microservices architecture: a single API gateway handles authentication, "
    "rate limiting, and routing to independent service engines (identity, wallet, transfer, ledger, "
    "payment, portfolio, rates, compliance, notification, and automation). Each engine is an isolated "
    "domain with its own data and scaling policy, so no single failure can bring down the platform.",
    styles['CozBody']
))
story.append(Paragraph(
    "<b>Important distinction:</b> AEGIS is the layer that moves and routes money. CZN is not required "
    "for AEGIS to route a transaction — it is the token used to pay AEGIS's resulting network/platform "
    "fees at a discount, and to access ecosystem rewards. CZN does not control or perform routing.",
    styles['CozBody']
))

# 5. CZN
story.append(Paragraph('5. CZN: The Ecosystem Token', styles['CozH1']))
story.append(Paragraph('Utility, not speculation.', styles['CozH2']))
story.append(Paragraph("CZN derives its value from real usage across the Cozanet ecosystem.", styles['CozBody']))
story.append(bullets([
    "<b>AEGIS fee discounts</b> — pay AEGIS's network/platform fees in CZN for automatic discounts.",
    "<b>Platform rewards</b> — earned for active usage, referrals, and ecosystem contribution.",
    "<b>Ecosystem access</b> — premium features and priority processing across Cozanet products.",
    "<b>Future governance</b> — participation in ecosystem decisions as the platform matures.",
]))
story.append(Paragraph('Token Specification', styles['CozH2']))
story.append(spec_table([
    ("TOKEN NAME", "Cozanet"),
    ("TOKEN SYMBOL", "CZN"),
    ("TOKEN STANDARD", "BEP-20 (BSC)"),
    ("TOTAL SUPPLY", "100,000,000,000,000,000,000 CZN"),
    ("TARGET SUPPLY (POST-BURN)", "400,000,000 CZN"),
    ("DECIMALS", "9"),
    ("BLOCKCHAIN", "BNB Smart Chain (BSC)"),
    ("CONTRACT ADDRESS", "0xE470E53147E199E6a6C02a50473fF8E84bD2d2CA"),
]))
story.append(Spacer(1, 6))
story.append(Paragraph("Always verify the contract address on BscScan before interacting with CZN.", styles['CozSmall']))
story.append(Paragraph(
    "As the Cozanet ecosystem grows, a portion of CZN in circulation will be periodically burned, "
    "reducing total supply toward a long-term target of 400,000,000 CZN.",
    styles['CozSmall']
))
story.append(Spacer(1, 10))
story.append(Paragraph('Token Distribution', styles['CozH2']))
story.append(spec_table([
    ("Ecosystem Growth", "35%"),
    ("Team & Advisors", "20%"),
    ("Community Rewards", "20%"),
    ("Treasury", "15%"),
    ("Early Backers", "10%"),
]))
story.append(Spacer(1, 6))
story.append(Paragraph(
    "Vesting schedules apply to all non-ecosystem allocations (team, advisors, treasury, early "
    "backers). Full vesting terms and unlock schedules are published in the transparency report.",
    styles['CozSmall']
))

# 6. Technology
story.append(Paragraph('6. Technology & Architecture', styles['CozH1']))
story.append(Paragraph('Architecture that scales with ambition.', styles['CozH2']))
story.append(bullets([
    "<b>API Gateway</b> — unified entry point handling auth, rate limiting, and intelligent routing to backend engines.",
    "<b>Microservices</b> — independent, horizontally-scaling containers per domain with auto-healing and zero-downtime deploys.",
    "<b>Multi-database strategy</b> — PostgreSQL for transactional data, Redis for caching, ClickHouse for analytics, vector databases for AI workloads.",
    "<b>Cloud-native</b> — Kubernetes orchestration across regions for low latency and disaster recovery.",
    "<b>Blockchain engine</b> — multi-chain indexing, transaction relaying, and smart contract interaction.",
]))

# 7. Security & Compliance
story.append(Paragraph('7. Security & Compliance', styles['CozH1']))
story.append(Paragraph('Security is the foundation, not a feature.', styles['CozH2']))
story.append(Paragraph(
    "Cozanet applies defense-in-depth across encryption (AES-256-GCM at rest, TLS 1.3 in transit), "
    "identity and access management (MFA, RBAC), key management (HSM-backed storage, multi-signature "
    "support), and continuous audit logging. Security programs, certifications, and audit dates "
    "referenced elsewhere on this site are being actively pursued and should be verified against "
    "current status before being cited externally (e.g. in exchange or listing applications).",
    styles['CozBody']
))
story.append(Paragraph(
    "On the compliance side: CZN is designed and marketed strictly as a utility token, not an "
    "investment, security, or financial instrument. Cozanet does not provide investment, financial, "
    "or legal advice, and does not engage in price manipulation or artificial volume creation.",
    styles['CozBody']
))

# 8. Roadmap
story.append(Paragraph('8. Roadmap', styles['CozH1']))
story.append(Paragraph('Building for the long term.', styles['CozH2']))
story.append(spec_table([
    ("Q1 2025 — AEGIS Core Launch", "Wallet infrastructure, payment processing, and business finance tools."),
    ("Q2 2025 — AI Financial Assistant", "Intelligent assistant for financial analysis and automated recommendations within AEGIS."),
    ("Q3 2025 — Cross-Chain Bridge", "Seamless asset transfers across multiple blockchain networks with unified liquidity."),
    ("Q4 2025 — Developer Platform v2", "Enhanced APIs, new SDKs, webhook system, and developer dashboard."),
    ("Q1 2026 — Enterprise Suite", "Compliance tools, advanced reporting, multi-entity management, white-label solutions."),
    ("Q2 2026 — CZN Ecosystem", "Full token utility integration across all products, governance framework, ecosystem rewards."),
]))

# 9. Team & Governance
story.append(Paragraph('9. Team & Governance', styles['CozH1']))
story.append(Paragraph('Built by engineers, for the long term.', styles['CozH2']))
story.append(Paragraph(
    "Cozanet is built and operated by a distributed, remote-first team of engineers, designers, and "
    "operators. The company's stated values — engineering excellence, security first, long-term "
    "thinking, user obsession, radical transparency, and continuous learning — govern day-to-day "
    "decision-making. As the ecosystem matures, CZN is designed to progressively enable community "
    "participation in ecosystem governance decisions.",
    styles['CozBody']
))

# 10. Risk Factors
story.append(Paragraph('10. Risk Factors & Disclaimer', styles['CozH1']))
story.append(Paragraph('Read before you rely on this document.', styles['CozH2']))
story.append(Paragraph(
    "This whitepaper is for informational purposes only and does not constitute investment, financial, "
    "legal, or tax advice, nor an offer or solicitation to buy or sell any security or financial "
    "instrument in any jurisdiction.",
    styles['CozBody']
))
story.append(Paragraph(
    "CZN is a utility token. It is not a security, equity, or debt instrument, and holding CZN does "
    "not entitle the holder to profits, dividends, or ownership in Cozanet. The value of CZN may "
    "fluctuate significantly and holders may lose some or all of their value. Never acquire CZN with "
    "funds you cannot afford to lose.",
    styles['CozBody']
))
story.append(Paragraph(
    "Roadmap items, timelines, and figures in this document are forward-looking statements and "
    "subject to change based on technical, regulatory, and market conditions. Token supply, "
    "distribution, and specification details are accurate as of the publish date above and are "
    "superseded by the live CZN token page and any official transparency report in case of conflict.",
    styles['CozBody']
))

story.append(Spacer(1, 0.4 * inch))
story.append(HRFlowable(width='100%', thickness=0.5, color=LIGHT_BORDER))
story.append(Spacer(1, 6))
story.append(Paragraph("Cozanet — technology that works for everyone. © 2026 Cozanet. All rights reserved.", styles['CozSmall']))

doc = SimpleDocTemplate(
    'cozanet-whitepaper.pdf', pagesize=LETTER,
    topMargin=0.9 * inch, bottomMargin=0.8 * inch, leftMargin=0.9 * inch, rightMargin=0.9 * inch,
    title='Cozanet Whitepaper v1.0', author='Cozanet',
)
doc.build(story)
print("Generated cozanet-whitepaper.pdf")
